name: Build Flet APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # TAMBAHKAN INI: Untuk memperbaiki error GTK dan library Linux
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libgles2-mesa-dev pkg-config

      # TAMBAHKAN INI: Untuk menyetujui lisensi Android secara otomatis
      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Install Dependencies
        run: |
          pip install flet pytz

      - name: Build APK
        run: flet build apk -vv
       
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flet-app-apk
          path: build/apk/*.apk

